In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

<IPython.core.display.Javascript object>

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [5]:
# List of functions explained 
function1 = np.concatenate  
function2 =  np.digitize 
function3 =  np.repeat
function4 =  np.squeeze 
function5 = np.random

In [7]:
# Example 1 - working 
# array with 11 elements, last element included
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Explanation about example

In [8]:
# Example 2 - working
# array with 11 elements, last element not included
np.linspace(0,10,11,endpoint=False)

array([0.        , 0.90909091, 1.81818182, 2.72727273, 3.63636364,
       4.54545455, 5.45454545, 6.36363636, 7.27272727, 8.18181818,
       9.09090909])

Explanation about example

In [11]:
import numpy 

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [17]:
import jovian

In [19]:
jovian.commit('Assingment-3')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "singhabhishek/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/singhabhishek/numpy-array-operations


'https://jovian.ai/singhabhishek/numpy-array-operations'

## Function 2 - np.digitize 

Maybe you have never heard about this function, but it can be really useful working with continuous spaces in reinforcement learning. The numpy.digitize(x, bins, right=False) function has two arguments: (1) an input array x, and (2) an array of bins, returning the indices of the bins to which each value in input array belongs. 

In [20]:
# Example 1 - working
# Input array
x = np.array([0.5])

# Bins - 5 bins in total
bins = np.array([0,1,2,3])


In [21]:
# Digitize function - 0.5 belong to the bin 0<= 0.5 <1 - therefore returned index 1
np.digitize(x,bins)

array([1])

In [22]:
# Example 2 - working
# The input array can contain several inputs
x = np.array([-0.5,1,3.5])

# Digitize function
np.digitize(x,bins)

array([0, 2, 4])

Explanation about example- # array([0, 2, 4], dtype=int64)

In [23]:
# Example 3 - breaking (to illustrate when it breaks)
def discretize(location, grid):
    return tuple(int(np.digitize(l, g)) for l, g in zip(location, grid))

# grid - bins - we will consider any value lower than 1 bin 0 and any value larger than 4 bin 4
grid = [np.array([1,2,3,4]),np.array([1,2,3,4])]

In [24]:
location =[2.5,1.2]
print(discretize(location,grid))

(2, 1)


In [25]:
location =[4.5,0.2]
print(discretize(location,grid)

SyntaxError: unexpected EOF while parsing (180117526.py, line 2)

Some closing comments about when to use this function.

In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "singhabhishek/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/singhabhishek/numpy-array-operations


'https://jovian.ai/singhabhishek/numpy-array-operations'

## Function 3 - numpy.repeat

The numpy.repeat(a, repeats, axis=None) function repeats the elements of an array. The number of repetitions is specified by the second argument repeats.

In [27]:
# Example 1 - working
np.repeat(3,5)

array([3, 3, 3, 3, 3])

Explanation about example

In [28]:
# Example 2 - working
np.repeat('2015',5)

array(['2015', '2015', '2015', '2015', '2015'], dtype='<U4')

Explanation about example

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 4 - np.squeeze

Numpy library includes several constants such as not a number (Nan), infinity (inf) or pi. In computing, not a number is a numeric data type that can be interpreted as a value that is undefined. We can use not a number to represent missing or null values in Pandas. Unfortunately, dirty data sets contain null values with other denominations (e.g. Unknown, — , and n/a), making difficult to detect and drop them.

In [34]:
# Example 1 - working
# numpy array of shape (1,2,1)

arr = np.array([[[1],[1]]])

arr.shape

(1, 2, 1)

Explanation about example

In [35]:
# Example 2 - working
# squeeze out axis 2
arr2 = np.squeeze(arr,axis=2)
arr2
#array([[1, 1]])
arr2.shape

(1, 2)

Explanation about example

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [37]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "singhabhishek/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/singhabhishek/numpy-array-operations


'https://jovian.ai/singhabhishek/numpy-array-operations'

## Function 5 - np.random

The numpy.random.randint(low, high=None, size=None, dtype=’l’) function returns random integers from the interval [low,high). If high parameter is missing (None), the random numbers are selected from the interval [0,low). By default, a single random number(int) is returned. To generate a narray of random integers, the shape of the array is provided in the parameter size.

In [38]:
# Example 1 - working-- "numpy.random.randint"
# roll a dice 10 times
np.random.randint(1,7,size=10)

array([3, 1, 5, 1, 6, 6, 2, 1, 2, 5])

Explanation about example

In [39]:
# Example 2 - working--" numpy.random.choice"
# roll a dice 10 times
np.random.choice([1,2,3,4,5,6],size=10)

array([2, 4, 2, 5, 5, 5, 2, 5, 3, 5])

The numpy.random.choice(a, size=None, replace=True, p=None) returns a random sample from a given array. By default, a single value is returned. To return more elements, the output shape can be specified in the parameter size as we did before with the numpy.random.randint function.

In [40]:
# Example 3 - breaking (to illustrate when it breaks)--"numpy.random.binomial"
# we can obtain approximated probabilities by simulating a huge number of flips 
# probability of obtaining 4 head in 10 flips 
flips = np.random.binomial(10,0.5,size=int(1e6))
(flips==4).mean()

0.204806